version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies and building the Java application..."
      - mvn clean package -DskipTests
      - echo "Logging in to Amazon ECR..."
      #- aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 087770005543.dkr.ecr.ap-south-1.amazonaws.com
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPONAME .
        #- docker build -t maven .
      - docker tag $REPONAME:latest $REPOSITORY_URI:latest
        #- docker tag maven:latest 087770005543.dkr.ecr.ap-south-1.amazonaws.com/maven:latest

  post_build:
    commands:
      - echo "Pushing Docker images to Amazon ECR..."
      #- docker push 087770005543.dkr.ecr.ap-south-1.amazonaws.com/maven:latest
      - docker push $REPOSITORY_URI:latest
      - echo "Writing image definitions file..."
      - printf '[{"name":"my-container","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files: 
    - imagedefinitions.json

